server {
    listen 80;

    root /var/www/site;
    index index.php index.html;

    # NestJS backend
    location /api/ {
        proxy_pass         http://backend:3000/;
        proxy_http_version 1.1;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
    }

    # PHP файлы
    location ~ \.php$ {
        fastcgi_pass   site:9000;
        fastcgi_index  index.php;
        fastcgi_param  SCRIPT_FILENAME /var/www/site$fastcgi_script_name;
        include        fastcgi_params;
    }

    # Статика и HTML
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }
}
